### ISSUE TITLE
new image

### ISSUE THREAD

**Issue by hakao32** [RI-imaging/radontea#5]
Hello,
How can I make radon transfrom to custom image with radontea?

**Comment by paulmueller** [comment]
please elaborate

**Comment by hakao32** [comment]
I found this:
https://pycache.de/assets/tm_art_filter/tomographic_filter.py
A good application of radontea.
Let me ask another question, can I use radontea with Cuda?

**Comment by paulmueller** [comment]
No, sorry. radontea is based on numpy.
